In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
data = pd.read_csv('../data/household_power_consumption.txt',sep=';')

C:\Users\Kartik\AppData\Local\Temp\ipykernel_13048\63241992.py:1: DtypeWarning: Columns (2: Global_active_power, 3: Global_reactive_power, 4: Voltage, 5: Global_intensity, 6: Sub_metering_1, 7: Sub_metering_2) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv('../data/household_power_consumption.txt',sep=';')

In [3]:
data.head()

,Date,Time,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3
0,16/12/2006,17:24:00,4.216,0.418,234.840,18.400,0.000,1.000,17.0
1,16/12/2006,17:25:00,5.360,0.436,233.630,23.000,0.000,1.000,16.0
2,16/12/2006,17:26:00,5.374,0.498,233.290,23.000,0.000,2.000,17.0
3,16/12/2006,17:27:00,5.388,0.502,233.740,23.000,0.000,1.000,17.0
4,16/12/2006,17:28:00,3.666,0.528,235.680,15.800,0.000,1.000,17.0

<h2>Basic Data Evaluation</h2>

In [4]:
data.shape

(2075259, 9)

In [5]:
data.columns

Index(['Date', 'Time', 'Global_active_power', 'Global_reactive_power',
       'Voltage', 'Global_intensity', 'Sub_metering_1', 'Sub_metering_2',
       'Sub_metering_3'],
      dtype='str')

In [6]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 2075259 entries, 0 to 2075258
Data columns (total 9 columns):
 #   Column                 Dtype
---  ------                 -----
 0   Date                   str
 1   Time                   str
 2   Global_active_power    object
 3   Global_reactive_power  object
 4   Voltage                object
 5   Global_intensity       object
 6   Sub_metering_1         object
 7   Sub_metering_2         object
 8   Sub_metering_3         float64
dtypes: float64(1), object(6), str(2)
memory usage: 142.5+ MB

In [7]:
data.columns=data.columns.str.lower().str.strip()

In [8]:
data.isna().sum()

date                         0
time                         0
global_active_power          0
global_reactive_power        0
voltage                      0
global_intensity             0
sub_metering_1               0
sub_metering_2               0
sub_metering_3           25979
dtype: int64

In [9]:
data['global_active_power']

0          4.216
1          5.360
2          5.374
3          5.388
4          3.666
           ...
2075254    0.946
2075255    0.944
2075256    0.938
2075257    0.934
2075258    0.932
Name: global_active_power, Length: 2075259, dtype: object

In [10]:
data[data['sub_metering_3'].isna()]

,date,time,global_active_power,global_reactive_power,voltage,global_intensity,sub_metering_1,sub_metering_2,sub_metering_3
6839,21/12/2006,11:23:00,?,?,?,?,?,?,NaN
6840,21/12/2006,11:24:00,?,?,?,?,?,?,NaN
19724,30/12/2006,10:08:00,?,?,?,?,?,?,NaN
19725,30/12/2006,10:09:00,?,?,?,?,?,?,NaN
41832,14/1/2007,18:36:00,?,?,?,?,?,?,NaN
...,...,...,...,...,...,...,...,...,...
1990185,28/9/2010,19:09:00,?,?,?,?,?,?,NaN
1990186,28/9/2010,19:10:00,?,?,?,?,?,?,NaN
1990187,28/9/2010,19:11:00,?,?,?,?,?,?,NaN
1990188,28/9/2010,19:12:00,?,?,?,?,?,?,NaN
2027411,24/10/2010,15:35:00,?,?,?,?,?,?,NaN

In [11]:
data.eq('?').sum()

date                         0
time                         0
global_active_power      25979
global_reactive_power    25979
voltage                  25979
global_intensity         25979
sub_metering_1           25979
sub_metering_2           25979
sub_metering_3               0
dtype: int64

In [12]:
data=data.replace('?',np.nan)

In [13]:
data.isna().sum()

date                         0
time                         0
global_active_power      25979
global_reactive_power    25979
voltage                  25979
global_intensity         25979
sub_metering_1           25979
sub_metering_2           25979
sub_metering_3           25979
dtype: int64

In [14]:
data[data['global_active_power'].isna()][['date','time']].head(20)

              date      time
6839    21/12/2006  11:23:00
6840    21/12/2006  11:24:00
19724   30/12/2006  10:08:00
19725   30/12/2006  10:09:00
41832    14/1/2007  18:36:00
61909    28/1/2007  17:13:00
98254    22/2/2007  22:58:00
98255    22/2/2007  22:59:00
142588   25/3/2007  17:52:00
190497   28/4/2007  00:21:00
190498   28/4/2007  00:22:00
190499   28/4/2007  00:23:00
190500   28/4/2007  00:24:00
190501   28/4/2007  00:25:00
190502   28/4/2007  00:26:00
190503   28/4/2007  00:27:00
190504   28/4/2007  00:28:00
190505   28/4/2007  00:29:00
190506   28/4/2007  00:30:00
190507   28/4/2007  00:31:00

In [15]:
missing = data["global_active_power"].isna()

groups = missing.ne(missing.shift()).cumsum()

block_sizes = missing.groupby(groups).sum()

missing_blocks = block_sizes[block_sizes > 0]

print(missing_blocks)
print("Largest missing block:", missing_blocks.max())

global_active_power
2         2
4         2
6         1
8         1
10        2
       ...
134       1
136       1
138    7226
140    5237
142       1
Name: global_active_power, Length: 71, dtype: int64
Largest missing block: 7226

In [18]:
missing_blocks.sort_values(ascending=False).head(15)

global_active_power
138    7226
140    5237
14     3723
100    3305
118    3129
126    2027
104     891
32       83
78       70
34       47
70       43
84       38
26       33
88       24
38       21
Name: global_active_power, dtype: int64

In [22]:
missing_rows= data[data['global_active_power'].isna()]

In [24]:
missing_rows[['date','time']].head(20)

              date      time
6839    21/12/2006  11:23:00
6840    21/12/2006  11:24:00
19724   30/12/2006  10:08:00
19725   30/12/2006  10:09:00
41832    14/1/2007  18:36:00
61909    28/1/2007  17:13:00
98254    22/2/2007  22:58:00
98255    22/2/2007  22:59:00
142588   25/3/2007  17:52:00
190497   28/4/2007  00:21:00
190498   28/4/2007  00:22:00
190499   28/4/2007  00:23:00
190500   28/4/2007  00:24:00
190501   28/4/2007  00:25:00
190502   28/4/2007  00:26:00
190503   28/4/2007  00:27:00
190504   28/4/2007  00:28:00
190505   28/4/2007  00:29:00
190506   28/4/2007  00:30:00
190507   28/4/2007  00:31:00

In [25]:
numeric_cols = [
    "global_active_power",
    "global_reactive_power",
    "voltage",
    "global_intensity",
    "sub_metering_1",
    "sub_metering_2",
    "sub_metering_3"
]

In [26]:
data[numeric_cols]=data[numeric_cols].apply(pd.to_numeric,errors='coerce')

In [27]:
data.head()

,date,time,global_active_power,global_reactive_power,voltage,global_intensity,sub_metering_1,sub_metering_2,sub_metering_3
0,16/12/2006,17:24:00,4.216,0.418,234.84,18.4,0.0,1.0,17.0
1,16/12/2006,17:25:00,5.360,0.436,233.63,23.0,0.0,1.0,16.0
2,16/12/2006,17:26:00,5.374,0.498,233.29,23.0,0.0,2.0,17.0
3,16/12/2006,17:27:00,5.388,0.502,233.74,23.0,0.0,1.0,17.0
4,16/12/2006,17:28:00,3.666,0.528,235.68,15.8,0.0,1.0,17.0

In [28]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 2075259 entries, 0 to 2075258
Data columns (total 9 columns):
 #   Column                 Dtype
---  ------                 -----
 0   date                   str
 1   time                   str
 2   global_active_power    float64
 3   global_reactive_power  float64
 4   voltage                float64
 5   global_intensity       float64
 6   sub_metering_1         float64
 7   sub_metering_2         float64
 8   sub_metering_3         float64
dtypes: float64(7), str(2)
memory usage: 142.5 MB

In [29]:
data[numeric_cols].isna().sum()

global_active_power      25979
global_reactive_power    25979
voltage                  25979
global_intensity         25979
sub_metering_1           25979
sub_metering_2           25979
sub_metering_3           25979
dtype: int64

In [30]:
data['date_time']=pd.to_datetime(data['date']+" "+data['time'])

C:\Users\Kartik\AppData\Local\Temp\ipykernel_13048\2208523486.py:1: UserWarning: Parsing dates in %d/%m/%Y %H:%M:%S format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  data['date_time']=pd.to_datetime(data['date']+" "+data['time'])

In [37]:
data.head()

,date,time,date_time,global_active_power,global_reactive_power,voltage,global_intensity,sub_metering_1,sub_metering_2,sub_metering_3
0,16/12/2006,17:24:00,2006-12-16 17:24:00,4.216,0.418,234.84,18.4,0.0,1.0,17.0
1,16/12/2006,17:25:00,2006-12-16 17:25:00,5.360,0.436,233.63,23.0,0.0,1.0,16.0
2,16/12/2006,17:26:00,2006-12-16 17:26:00,5.374,0.498,233.29,23.0,0.0,2.0,17.0
3,16/12/2006,17:27:00,2006-12-16 17:27:00,5.388,0.502,233.74,23.0,0.0,1.0,17.0
4,16/12/2006,17:28:00,2006-12-16 17:28:00,3.666,0.528,235.68,15.8,0.0,1.0,17.0

In [36]:
col=data.pop('date_time')
data.insert(2,'date_time',col)